"""empty message

Revision ID: 8da278e7f6ac
Revises: 
Create Date: 2024-03-24 17:56:43.554136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da278e7f6ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paint_inventory',
    sa.Column('color', sa.Enum('blue', 'grey', 'black', 'white', 'purple', name='colormodel'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('color')
    )
    op.create_table('paint_status',
    sa.Column('color', sa.Enum('blue', 'grey', 'black', 'white', 'purple', name='colormodel'), nullable=False),
    sa.Column('status', sa.Enum('available', 'running_low', 'out_of_stock', name='statusmodel'), nullable=False),
    sa.PrimaryKeyConstraint('color')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('blue', 'grey', 'black', 'white', 'purple', name='colormodel'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('paint_status')
    op.drop_table('paint_inventory')
    op.drop_table('order')
    # ### end Alembic commands ###
